enabled=yes
# skip once per chapter, or every time it's re-entered (e.g. seeking back)
skip_once=yes
# add custom categories as "name+pattern1/pattern2;name2+pattern1", see
# https://github.com/po5/chapterskip for syntax
categories=
# which built-in categories to skip: prologue, opening, ending, preview
# (separate multiple with ;)
skip=opening;ending;preview
